name: Pages
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Autodoc
      run: |
        pip install sphinx myst-parser furo
        cd doc
        sphinx-apidoc -f --private --ext-autodoc --separate -o . ../metest/

    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        documentation_path: doc/

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages